<?php
/**
 * The Lacey Ledger — time-based one-time passwords (RFC 6238).
 *
 * The second factor. Google Sign-In proves who you are; this proves you are
 * holding the phone. Codes are generated by Google Authenticator (or any
 * other authenticator app) from a secret that only ever exists in
 * ledger-auth-config.php and on the phone.
 *
 * Deliberately independent of the database: if MySQL is down you should still
 * be able to get in and look at why.
 */

declare(strict_types=1);

/** Decode a base32 secret (RFC 4648, no padding required). */
function totp_base32_decode(string $b32): string
{
    $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    $b32 = strtoupper(preg_replace('/[^A-Za-z2-7]/', '', $b32));

    $bits = '';
    $out  = '';
    foreach (str_split($b32) as $ch) {
        $idx = strpos($alphabet, $ch);
        if ($idx === false) {
            continue;
        }
        $bits .= str_pad(decbin($idx), 5, '0', STR_PAD_LEFT);
    }
    foreach (str_split($bits, 8) as $byte) {
        if (strlen($byte) === 8) {
            $out .= chr(bindec($byte));
        }
    }
    return $out;
}

/** Encode raw bytes as base32, the form authenticator apps expect. */
function totp_base32_encode(string $raw): string
{
    $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    $bits = '';
    foreach (str_split($raw) as $ch) {
        $bits .= str_pad(decbin(ord($ch)), 8, '0', STR_PAD_LEFT);
    }
    $out = '';
    foreach (str_split($bits, 5) as $chunk) {
        $out .= $alphabet[bindec(str_pad($chunk, 5, '0', STR_PAD_RIGHT))];
    }
    return $out;
}

/** A fresh 160-bit secret, the size RFC 4226 recommends. */
function totp_new_secret(): string
{
    return totp_base32_encode(random_bytes(20));
}

/** The code for one 30-second step. */
function totp_code_at(string $secretB32, int $counter, int $digits = 6, string $algo = 'sha1'): string
{
    $key  = totp_base32_decode($secretB32);
    $hash = hash_hmac($algo, pack('N*', 0, $counter), $key, true);

    // Dynamic truncation, RFC 4226 §5.3.
    $offset = ord($hash[strlen($hash) - 1]) & 0x0F;
    $value  = ((ord($hash[$offset])     & 0x7F) << 24)
            | ((ord($hash[$offset + 1]) & 0xFF) << 16)
            | ((ord($hash[$offset + 2]) & 0xFF) << 8)
            |  (ord($hash[$offset + 3]) & 0xFF);

    return str_pad((string) ($value % (10 ** $digits)), $digits, '0', STR_PAD_LEFT);
}

/** The step number for a moment in time. */
function totp_counter(?int $at = null, int $period = 30): int
{
    return intdiv($at ?? time(), $period);
}

/**
 * Check a code, allowing one step either side for clock drift.
 *
 * Returns the accepted step number, or null. The caller must record the
 * returned step and refuse anything <= it next time, so a code that is
 * shoulder-surfed cannot be replayed inside its own 30-second window.
 */
function totp_verify(
    string $secretB32,
    string $code,
    ?int $lastUsedCounter = null,
    int $window = 1,
    ?int $at = null,
    int $digits = 6
): ?int {
    $code = preg_replace('/\D/', '', $code);
    if (strlen($code) !== $digits) {
        return null;
    }

    $now = totp_counter($at);
    for ($i = -$window; $i <= $window; $i++) {
        $counter = $now + $i;
        if ($lastUsedCounter !== null && $counter <= $lastUsedCounter) {
            continue;   // already spent
        }
        if (hash_equals(totp_code_at($secretB32, $counter, $digits), $code)) {
            return $counter;
        }
    }
    return null;
}

/** The otpauth:// URI an authenticator app enrols from. */
function totp_uri(string $secretB32, string $account, string $issuer = 'The Lacey Ledger'): string
{
    return 'otpauth://totp/' . rawurlencode($issuer) . ':' . rawurlencode($account)
         . '?secret=' . $secretB32
         . '&issuer=' . rawurlencode($issuer)
         . '&algorithm=SHA1&digits=6&period=30';
}

/** The secret in the four-character groups that are easier to type in. */
function totp_grouped(string $secretB32): string
{
    return trim(chunk_split($secretB32, 4, ' '));
}
